name: flutter_firebase_crud_lab
description: A Flutter project demonstrating basic CRUD operations with Firebase.
publish_to: 'none' # Set to 'none' to prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase core and Firestore
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.0

  # Icons and UI enhancements
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.4

  # Optional enhancements (for animated UI)
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment if you add images or fonts
  # assets:
  #   - assets/images/

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
