// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw-boSWwWGd1BQ4pYC4tafdK_vCVfP_jQ',
    appId: '1:729507077058:web:bf2fae3bd07907ff3d545b',
    messagingSenderId: '729507077058',
    projectId: 'fir-project-9872d',
    authDomain: 'fir-project-9872d.firebaseapp.com',
    databaseURL: 'https://fir-project-9872d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-project-9872d.firebasestorage.app',
    measurementId: 'G-5PE4KJGS72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADHZ-FLlzuq68w_mqpR3ghb94Xr7rmPaE',
    appId: '1:729507077058:android:46dd3489003eecf43d545b',
    messagingSenderId: '729507077058',
    projectId: 'fir-project-9872d',
    databaseURL: 'https://fir-project-9872d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-project-9872d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLbBvxkDo8RjpYGRqsNReBrdwBeFsvzBQ',
    appId: '1:729507077058:ios:66c23c8ec43a017b3d545b',
    messagingSenderId: '729507077058',
    projectId: 'fir-project-9872d',
    databaseURL: 'https://fir-project-9872d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-project-9872d.firebasestorage.app',
    iosBundleId: 'com.example.flutterStateManagementLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLbBvxkDo8RjpYGRqsNReBrdwBeFsvzBQ',
    appId: '1:729507077058:ios:66c23c8ec43a017b3d545b',
    messagingSenderId: '729507077058',
    projectId: 'fir-project-9872d',
    databaseURL: 'https://fir-project-9872d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-project-9872d.firebasestorage.app',
    iosBundleId: 'com.example.flutterStateManagementLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw-boSWwWGd1BQ4pYC4tafdK_vCVfP_jQ',
    appId: '1:729507077058:web:16ff2d3d19bc60413d545b',
    messagingSenderId: '729507077058',
    projectId: 'fir-project-9872d',
    authDomain: 'fir-project-9872d.firebaseapp.com',
    databaseURL: 'https://fir-project-9872d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-project-9872d.firebasestorage.app',
    measurementId: 'G-8T1J6R76MP',
  );

}